from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
import urllib.error
import urllib.request
from collections import Counter
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from visualize import generate_visualizations


@dataclass(frozen=True)
class SkillConfig:
    project_root: Path
    skill_path: Path
    raw_dir: Path
    standardized_output: Path
    structured_output: Path
    report_output: Path
    figures_dir: Path
    normalize_prompt: Path
    extract_prompt: Path
    report_prompt: Path
    schema_path: Path


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def read_json(path: Path) -> Any:
    return json.loads(read_text(path))


def write_json(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def write_text(path: Path, data: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(data.rstrip() + "\n", encoding="utf-8")


def load_env_file(path: Path) -> bool:
    if not path.exists():
        return False

    for line in read_text(path).splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, value = stripped.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key and key not in os.environ:
            os.environ[key] = value
    return True


def parse_skill(project_root: Path) -> SkillConfig:
    skill_path = project_root / "agent" / "SKILL.md"
    skill_text = read_text(skill_path)

    def extract_path(pattern: str, fallback: str) -> Path:
        match = re.search(pattern, skill_text)
        value = match.group(1) if match else fallback
        return project_root / value

    prompt_paths = re.findall(r"Use `([^`]+)` for ([^.]+)\.", skill_text)
    prompts = {Path(path).name: project_root / "agent" / path for path, _ in prompt_paths}

    return SkillConfig(
        project_root=project_root,
        skill_path=skill_path,
        raw_dir=extract_path(r"Raw news input lives in `([^`]+)`", "data/raw/"),
        standardized_output=extract_path(
            r"Standardized intermediate output should be written to `([^`]+)`",
            "data/processed/normalized_data.json",
        ),
        structured_output=extract_path(
            r"Final structured event output should be written to `([^`]+)`",
            "data/processed/structured_data.json",
        ),
        report_output=extract_path(
            r"Daily report output should be written to `([^`]+)`",
            "data/processed/daily_report.md",
        ),
        figures_dir=extract_path(
            r"Visualization outputs should be written to `([^`]+)`",
            "data/processed/figures/",
        ),
        normalize_prompt=prompts.get(
            "normalize_news.md",
            project_root / "agent" / "prompts" / "normalize_news.md",
        ),
        extract_prompt=prompts.get(
            "extract_structured_data.md",
            project_root / "agent" / "prompts" / "extract_structured_data.md",
        ),
        report_prompt=prompts.get(
            "generate_daily_report.md",
            project_root / "agent" / "prompts" / "generate_daily_report.md",
        ),
        schema_path=project_root / "agent" / "schema.json",
    )


class LLMClient:
    def __init__(self, dry_run: bool = False):
        self.dry_run = dry_run
        self.api_key = os.getenv("LLM_API_KEY") or os.getenv("OPENAI_API_KEY")
        self.model = os.getenv("LLM_MODEL") or os.getenv("OPENAI_MODEL")
        self.base_url = (
            os.getenv("LLM_BASE_URL")
            or os.getenv("OPENAI_BASE_URL")
            or "https://api.openai.com/v1"
        ).rstrip("/")

    def complete(self, prompt: str, input_data: Any, *, expect_json: bool) -> str:
        if self.dry_run:
            raise RuntimeError("Dry-run responses are generated by deterministic local helpers.")
        if not self.api_key:
            raise RuntimeError("Missing LLM_API_KEY or OPENAI_API_KEY. Add it to .env or export it.")
        if not self.model:
            raise RuntimeError("Missing LLM_MODEL or OPENAI_MODEL. Add it to .env or export it.")

        user_content = format_user_input(input_data, expect_json=expect_json)
        payload = {
            "model": self.model,
            "messages": [
                {"role": "system", "content": prompt},
                {"role": "user", "content": user_content},
            ],
            "temperature": 0.2,
        }

        request = urllib.request.Request(
            f"{self.base_url}/chat/completions",
            data=json.dumps(payload).encode("utf-8"),
            headers={
                "Authorization": f"Bearer {self.api_key}",
                "Content-Type": "application/json",
                **optional_openrouter_headers(),
            },
            method="POST",
        )

        try:
            with urllib.request.urlopen(request, timeout=120) as response:
                result = json.loads(response.read().decode("utf-8"))
        except urllib.error.HTTPError as exc:
            body = exc.read().decode("utf-8", errors="replace")
            raise RuntimeError(f"LLM request failed: {exc.code} {body}") from exc

        return result["choices"][0]["message"]["content"]


def optional_openrouter_headers() -> dict[str, str]:
    headers = {}
    site_url = os.getenv("OPENROUTER_SITE_URL")
    app_name = os.getenv("OPENROUTER_APP_NAME")
    if site_url:
        headers["HTTP-Referer"] = site_url
    if app_name:
        headers["X-OpenRouter-Title"] = app_name
    return headers


def format_user_input(input_data: Any, *, expect_json: bool) -> str:
    serialized = json.dumps(input_data, ensure_ascii=False, indent=2)
    if expect_json:
        return "Return valid JSON only. Input data:\n\n```json\n" + serialized + "\n```"
    return "Return Markdown only. Input data:\n\n```json\n" + serialized + "\n```"


def parse_json_response(text: str) -> Any:
    cleaned = text.strip()
    fence = re.search(r"```(?:json)?\s*(.*?)```", cleaned, re.DOTALL)
    if fence:
        cleaned = fence.group(1).strip()
    data = json.loads(cleaned)
    if isinstance(data, dict) and len(data) == 1:
        only_value = next(iter(data.values()))
        if isinstance(only_value, list):
            return only_value
    return data


def load_raw_news(raw_dir: Path) -> list[dict[str, Any]]:
    preferred = raw_dir / "raw_news.json"
    path = preferred if preferred.exists() else next(raw_dir.glob("*.json"), None)
    if path is None:
        raise FileNotFoundError(f"No raw JSON file found in {raw_dir}")
    data = read_json(path)
    if not isinstance(data, list):
        raise ValueError(f"Raw news file must contain a JSON array: {path}")
    return data


def validate_standardized(records: Any) -> list[dict[str, Any]]:
    required = {
        "news_id",
        "title",
        "source",
        "source_type",
        "url",
        "published_at",
        "language",
        "standardized_summary",
        "key_facts",
        "evidence_snippets",
    }
    if not isinstance(records, list):
        raise ValueError("Standardized output must be a JSON array.")
    for index, record in enumerate(records):
        missing = required - set(record)
        if missing:
            raise ValueError(f"Standardized record {index} missing fields: {sorted(missing)}")
    return records


def validate_structured(events: Any, schema: dict[str, Any], known_news_ids: set[str]) -> list[dict[str, Any]]:
    required = set(schema["items"]["required"])
    event_type_enum = set(schema["items"]["properties"]["event_type"]["enum"])
    topic_enum = set(schema["items"]["properties"]["topic"]["enum"])
    signal_enum = set(schema["items"]["properties"]["signals"]["items"]["enum"])

    if not isinstance(events, list):
        raise ValueError("Structured output must be a JSON array.")
    for index, event in enumerate(events):
        missing = required - set(event)
        if missing:
            raise ValueError(f"Event {index} missing fields: {sorted(missing)}")
        if event["event_type"] not in event_type_enum:
            raise ValueError(f"Event {index} has invalid event_type: {event['event_type']}")
        if event["topic"] not in topic_enum:
            raise ValueError(f"Event {index} has invalid topic: {event['topic']}")
        invalid_signals = set(event["signals"]) - signal_enum
        if invalid_signals:
            raise ValueError(f"Event {index} has invalid signals: {sorted(invalid_signals)}")
        unknown_sources = set(event["source_news_ids"]) - known_news_ids
        if unknown_sources:
            raise ValueError(f"Event {index} references unknown news ids: {sorted(unknown_sources)}")

        importance = event["importance"]
        score_sum = sum(
            importance[key]
            for key in [
                "impact_score",
                "source_score",
                "novelty_score",
                "relevance_score",
                "urgency_score",
            ]
        )
        if importance["total_score"] != score_sum:
            importance["total_score"] = score_sum

    return sort_events(events)


def sort_events(events: list[dict[str, Any]]) -> list[dict[str, Any]]:
    return sorted(
        events,
        key=lambda event: (
            event["importance"]["total_score"],
            event["importance"]["urgency_score"],
            event["importance"]["impact_score"],
            len(event["source_news_ids"]),
            event["event_date"],
        ),
        reverse=True,
    )


def normalize(config: SkillConfig, client: LLMClient) -> list[dict[str, Any]]:
    raw_news = load_raw_news(config.raw_dir)
    if client.dry_run:
        standardized = dry_run_normalize(raw_news)
    else:
        prompt = read_text(config.normalize_prompt)
        response = client.complete(prompt, raw_news, expect_json=True)
        standardized = parse_json_response(response)
    standardized = validate_standardized(standardized)
    write_json(config.standardized_output, standardized)
    return standardized


def extract(config: SkillConfig, client: LLMClient) -> list[dict[str, Any]]:
    standardized = read_json(config.standardized_output)
    known_news_ids = {record["news_id"] for record in standardized}
    schema = read_json(config.schema_path)
    if client.dry_run:
        events = dry_run_extract(standardized)
    else:
        prompt = read_text(config.extract_prompt)
        input_data = {"schema": schema, "records": standardized}
        response = client.complete(prompt, input_data, expect_json=True)
        events = parse_json_response(response)
    events = validate_structured(events, schema, known_news_ids)
    write_json(config.structured_output, events)
    return events


def report(config: SkillConfig, client: LLMClient) -> str:
    events = read_json(config.structured_output)
    if client.dry_run:
        markdown = dry_run_report(events)
    else:
        prompt = read_text(config.report_prompt)
        response = client.complete(prompt, build_report_input(events), expect_json=False)
        markdown = response.strip()
    markdown = reorder_report_sections(markdown)
    write_text(config.report_output, markdown)
    return markdown


def visualize(config: SkillConfig) -> list[Path]:
    events = read_json(config.structured_output)
    figures = generate_visualizations(events, config.figures_dir)
    append_visualization_links(config.report_output, figures)
    return figures


def append_visualization_links(report_path: Path, figures: list[Path]) -> None:
    if not report_path.exists():
        return
    report = read_text(report_path)
    marker = "## 可视化图表"
    if marker in report:
        report = report.split(marker, 1)[0].rstrip()

    lines = ["", marker, ""]
    for figure in figures:
        relative_path = figure.relative_to(report_path.parent)
        version = file_cache_key(figure)
        title = figure.stem.replace("_", " ").title()
        lines.extend([f"![{title}]({relative_path.as_posix()}?v={version})", ""])
    write_text(report_path, report + "\n" + "\n".join(lines))


def file_cache_key(path: Path) -> str:
    return hashlib.sha1(path.read_bytes()).hexdigest()[:8]


def reorder_report_sections(markdown: str) -> str:
    title, sections = split_markdown_sections(markdown)
    desired_order = [
        "今日一句话判断",
        "Top 3-5 重要事件",
        "Top 3 重要事件",
        "重要事件深度分析",
        "结构化事件表",
        "可视化图表",
    ]
    skip_sections = {"数据概览", "趋势判断", "风险与机会提示"}

    output = [title.strip() or "# AI 舆情分析日报"]
    used = set()
    for heading in desired_order:
        if heading in sections and heading not in used:
            normalized_heading = "Top 3 重要事件" if heading == "Top 3-5 重要事件" else heading
            body = normalize_report_section(normalized_heading, sections[heading])
            output.extend(["", f"## {normalized_heading}", "", body.strip()])
            used.add(heading)

    for heading, body in sections.items():
        if heading in used or heading in skip_sections:
            continue
        output.extend(["", f"## {heading}", "", body.strip()])

    return "\n".join(output).rstrip()


def normalize_report_section(heading: str, body: str) -> str:
    if heading == "Top 3 重要事件":
        return keep_first_numbered_items(body, 3)
    if heading == "重要事件深度分析":
        return keep_first_subsections(body, 3)
    return body


def keep_first_numbered_items(markdown: str, limit: int) -> str:
    lines = markdown.strip().splitlines()
    kept = []
    count = 0
    for line in lines:
        if re.match(r"^\d+\.\s+", line.strip()):
            count += 1
            if count > limit:
                continue
        if count <= limit:
            kept.append(line)
    return "\n".join(kept).strip()


def keep_first_subsections(markdown: str, limit: int) -> str:
    matches = list(re.finditer(r"^###\s+", markdown, re.MULTILINE))
    if len(matches) <= limit:
        return markdown.strip()
    return markdown[: matches[limit].start()].strip()


def split_markdown_sections(markdown: str) -> tuple[str, dict[str, str]]:
    matches = list(re.finditer(r"^##\s+(.+?)\s*$", markdown, re.MULTILINE))
    if not matches:
        return markdown, {}
    title = markdown[: matches[0].start()].strip()
    sections = {}
    for index, match in enumerate(matches):
        heading = match.group(1).strip()
        start = match.end()
        end = matches[index + 1].start() if index + 1 < len(matches) else len(markdown)
        sections[heading] = markdown[start:end].strip()
    return title, sections


def build_report_input(events: list[dict[str, Any]]) -> dict[str, Any]:
    sorted_events = sort_events(events)
    event_dates = [event["event_date"] for event in sorted_events if event.get("event_date")]
    signals = [
        signal
        for event in sorted_events
        for signal in event.get("signals", [])
    ]
    return {
        "metadata": {
            "event_count": len(sorted_events),
            "date_range": {
                "start": min(event_dates) if event_dates else None,
                "end": max(event_dates) if event_dates else None,
            },
            "event_type_counts": dict(Counter(event["event_type"] for event in sorted_events)),
            "topic_counts": dict(Counter(event["topic"] for event in sorted_events)),
            "signal_counts": dict(Counter(signals)),
            "top_event_ids": [event["event_id"] for event in sorted_events[:5]],
        },
        "events": sorted_events,
    }


def dry_run_normalize(raw_news: list[dict[str, Any]]) -> list[dict[str, Any]]:
    records = []
    for item in raw_news:
        facts = split_facts(item.get("content", ""))[:3]
        records.append(
            {
                "news_id": item["news_id"],
                "title": item["title"],
                "source": item["source"],
                "source_type": item["source_type"],
                "url": item["url"],
                "published_at": item["published_at"],
                "language": item["language"],
                "standardized_summary": " ".join(facts[:2]) or item["title"],
                "key_facts": facts or [item["title"]],
                "evidence_snippets": facts[:2] or [item["title"]],
            }
        )
    return records


def dry_run_extract(records: list[dict[str, Any]]) -> list[dict[str, Any]]:
    events = []
    for index, record in enumerate(records, start=1):
        event_type, topic, signals = classify_dry_run(record)
        event = {
            "event_id": f"event_{index:03d}",
            "event_name": record["title"],
            "event_description": record["standardized_summary"],
            "event_date": record["published_at"],
            "event_type": event_type,
            "topic": topic,
            "entities": [
                {
                    "name": record["source"],
                    "type": "company",
                    "role": "source",
                }
            ],
            "source_news_ids": [record["news_id"]],
            "key_points": pad_list(record["key_facts"], 2, record["standardized_summary"])[:4],
            "importance": {
                "impact_score": 3,
                "source_score": source_score(record["source_type"]),
                "novelty_score": 3,
                "relevance_score": 4,
                "urgency_score": 3,
                "total_score": 16,
                "reason": "Dry-run heuristic score. Use real LLM extraction for final analysis.",
            },
            "signals": signals,
            "why_it_matters": "Dry-run event generated to validate the pipeline flow.",
            "evidence": [
                {
                    "news_id": record["news_id"],
                    "text": record["evidence_snippets"][0],
                    "used_for": "event_description",
                }
            ],
        }
        event["importance"]["total_score"] = sum(
            event["importance"][key]
            for key in [
                "impact_score",
                "source_score",
                "novelty_score",
                "relevance_score",
                "urgency_score",
            ]
        )
        events.append(event)
    return events


def dry_run_report(events: list[dict[str, Any]]) -> str:
    top_events = sort_events(events)[:3]
    lines = [
        "# AI 舆情分析日报",
        "",
        "## 今日一句话判断",
        "",
        "AI agent、安全治理、模型能力与基础设施仍是本批新闻中的主要观察方向。",
        "",
        "## Top 3 重要事件",
        "",
    ]
    for event in top_events:
        lines.append(
            f"- {event['event_name']} "
            f"(score={event['importance']['total_score']}, sources={', '.join(event['source_news_ids'])})"
        )
    lines.extend(
        [
            "",
            "## 重要事件深度分析",
            "",
            "dry-run 模式不会做真实深度分析；请使用真实 LLM 调用生成最终日报。",
            "",
            "## 数据概览",
            "",
            f"- 本次共处理 {len(events)} 个结构化事件。",
            "- 当前报告由 dry-run 模式生成，只用于验证 agent pipeline。",
            "",
            "## 结构化事件表",
            "",
            "| Event | Type | Topic | Score | Sources |",
            "| --- | --- | --- | ---: | --- |",
        ]
    )
    for event in top_events:
        lines.append(
            f"| {event['event_name']} | {event['event_type']} | {event['topic']} | "
            f"{event['importance']['total_score']} | {', '.join(event['source_news_ids'])} |"
        )
    return "\n".join(lines)


def split_facts(text: str) -> list[str]:
    parts = re.split(r"(?<=[.!?。！？])\s+", text.strip())
    return [part.strip() for part in parts if part.strip()]


def pad_list(values: list[str], size: int, fallback: str) -> list[str]:
    output = list(values)
    while len(output) < size:
        output.append(fallback)
    return output


def source_score(source_type: str) -> int:
    if source_type in {"official_blog", "research_paper"}:
        return 5
    if source_type in {"financial_media", "technology_media", "business_media"}:
        return 4
    return 3


def classify_dry_run(record: dict[str, Any]) -> tuple[str, str, list[str]]:
    text = f"{record['title']} {record['standardized_summary']}".lower()
    if any(word in text for word in ["hack", "cyber", "security", "sandbox", "breach"]):
        return "security_analysis", "AI cybersecurity", ["security_risk", "agent_governance"]
    if any(word in text for word in ["watermark", "eu ai act", "regulation", "sanders"]):
        return "policy_regulation", "AI policy", ["regulatory_pressure"]
    if any(word in text for word in ["chip", "compute", "data center", "infrastructure"]):
        return "ai_infrastructure", "AI infrastructure", ["cost_pressure", "supply_chain_risk"]
    if any(word in text for word in ["open-weight", "open source", "open-source"]):
        return "open_source", "open-source ecosystem", ["open_source_momentum"]
    if any(word in text for word in ["assistant", "agent", "claude code"]):
        return "agent_platform", "AI agent", ["developer_opportunity", "agent_governance"]
    if any(word in text for word in ["stock", "ipo", "investor"]):
        return "market_competition", "AI business", ["competition", "business_model_shift"]
    return "product_update", "enterprise AI", ["enterprise_adoption"]


def run_pipeline(step: str, dry_run: bool, env_file: str | None) -> None:
    project_root = Path(__file__).resolve().parents[1]
    config = parse_skill(project_root)
    env_path = Path(env_file).expanduser() if env_file else project_root / ".env"
    env_loaded = load_env_file(env_path)
    client = LLMClient(dry_run=dry_run)

    print(f"Loaded skill: {config.skill_path}")
    if env_loaded:
        print(f"Loaded env file: {env_path}")
    elif not dry_run:
        print(f"Env file not found, using shell environment: {env_path}")
    if step in {"normalize", "all"}:
        records = normalize(config, client)
        print(f"Wrote {len(records)} standardized records: {config.standardized_output}")
    if step in {"extract", "all"}:
        events = extract(config, client)
        print(f"Wrote {len(events)} structured events: {config.structured_output}")
    if step in {"report", "all"}:
        report(config, client)
        print(f"Wrote daily report: {config.report_output}")
    if step in {"visualize", "all"}:
        figures = visualize(config)
        print(f"Wrote {len(figures)} visualizations: {config.figures_dir}")


def main() -> int:
    parser = argparse.ArgumentParser(description="Run the AI news analysis skill agent.")
    parser.add_argument(
        "--step",
        choices=["normalize", "extract", "report", "visualize", "all"],
        default="all",
        help="Pipeline step to run.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Run deterministic local placeholders instead of calling an LLM.",
    )
    parser.add_argument(
        "--env-file",
        default=None,
        help="Optional path to a .env file. Defaults to project .env.",
    )
    args = parser.parse_args()

    try:
        run_pipeline(step=args.step, dry_run=args.dry_run, env_file=args.env_file)
    except Exception as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
